### ISSUE TITLE
problems when X is not double precision

### ISSUE THREAD

**Issue by stephens999** [pcarbo/varbvs#16]
I have seen instances where I had to use:

storage.mode(X) <- "double"

before varbvs would run. Maybe the current check on X is too strict?

**Comment by pcarbo** [comment]
@stephens999 Thanks, I remember you posted something about this on Slack earlier, but forgot to reply. My reasoning for reporting an error rather coercing to double is that will create a copy of `X`. In varbvs, I avoid creating copies of `X` in all circumstances (that is, I do not make any changes to `X`) because `X` could be very large (e.g., in GWAS, over 10 GB).

**Comment by stephens999** [comment]
That makes sense.

But why do you need x to be double rather than numeric?

**Comment by pcarbo** [comment]
@stephens999 Yes, in principle it could work with integers as well. I suppose it would be a bit of a headache to implement and test since for both integers and floating-point numbers since some methods do expect floating-point. Perhaps more importantly, the C code expects a double-precision floating point.

**Comment by stephens999** [comment]
So maybe for now, provide a message to suggest the solution in cases where
x is numeric, since the solution was far from obvious to me.

**Comment by pcarbo** [comment]
@stephens999 Yes, that is exactly what I have done. Thanks.

**Comment by pcarbo** [comment]
@stephens999 I relented---I now automatically convert to double-precision when `X` is another numeric type (e.g., integer).
