### ISSUE TITLE
Definitions of sa are different between varbvs 1.0 and 2.0

### ISSUE THREAD

**Issue by xiangzhu** [pcarbo/varbvs#9]
Definition in varbvs 1.0 ([source](https://github.com/xiangzhu/varbvs/blob/master/varbvs-201501/MATLAB/varbvs.m#L24)):
```matlab
% Inputs SIGMA, SA and LOGODDS are the hyperparameters. SIGMA and SA are
% scalars. SIGMA specifies the variance of the residual, and SA*SIGMA is the
% prior variance of the coefficients.
```

Definition in varbvs 2.0 ([source](https://github.com/pcarbo/varbvs/blob/master/varbvs-MATLAB/varbvs.m#L118)):
```matlab
%    Hyperparameter sa is the prior variance of regression coefficients for
%    variables that are included in the model.
```

I did not notice this difference until I saw unexpected results of varbvs 2.0 in simulations.

**Comment by xiangzhu** [comment]
The definitions of `logodds` are also different, which I figured out after seeing the simulation results.

Definition in varbvs 1.0 ([source](https://github.com/xiangzhu/varbvs/blob/master/varbvs-201501/MATLAB/varbvs.m#L26)):
```matlab
% LOGODDS is the prior log-odds of
% inclusion for each variable. It is equal to LOGODDS = LOG(Q./(1-Q)), where
% Q is the prior probability that each variable is included in the linear
% model of Y (i.e. the prior probability that its coefficient is not zero).
```

Definition in varbvs 2.0 ([source](https://github.com/pcarbo/varbvs/blob/master/varbvs-MATLAB/varbvs.m#L121)):
```matlab
%    Hyperparameter logodds is the
%    prior log-odds that a variable is included in the regression model; it
%    is defined as logodds = log10(q/(1-q)), where q is the prior
```

**Comment by pcarbo** [comment]
Thanks, Xiang, for pointing out these discrepancies in the description. The prior variance is still scaled by sigma, I just did not make that clear, so I have tried to better clarify that in the function help. 

For the prior log-odds, you are right that it is defined using base-10 because I find that more natural. However, you will see that in the calls to the "helper functions" (e.g., varbvsnorm) I multiply the logodds by log(10) because the helper functions define the log(10) in terms of the natural log for ease of implementation. I realize it is a bit confusing.

Please continue to point out anything that seems odd or confusing.

**Comment by xiangzhu** [comment]
Thanks for the reply. Can you confirm the following?

The prior variance of the regression coefficients ("beta")
- varbvs 1.0: `sigma * sa`
- varbvs 2.0: `sa`

In my current simulations, I set `sa` as the prior variance. Let me know if this is wrong.

According to your reply, it seems both should be `sigma * sa`?
> The prior variance is still scaled by sigma, I just did not make that clear

**Comment by pcarbo** [comment]
Yes, that is correct. In other words,

beta ~ N(0, sigma * sa)

For logistic regression, sigma = 1. You typically want the regression coefficients to be scaled by sigma so that the prior is invariant to the scale of Y. Let me know if that's still not clear.

**Comment by xiangzhu** [comment]
It seems I am wrong. My current codes are based on:

beta ~ N(0, sa)

I need to re-run the simulations. Thanks!
